name: GitHub Readme Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Stats
        uses: stats-organization/github-readme-stats-action@main
        with:
          card: stats
          path: stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages
        uses: stats-organization/github-readme-stats-action@main
        with:
          card: top-langs
          path: top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}
