name: GitHub Readme Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Stats
        uses: stats-organization/github-readme-stats-action@main
        with:
          username: JuanRRaFdez
          template: default
          output_path: stats.svg

      - name: Generate Streak
        uses: stats-organization/github-readme-stats-action@main
        with:
          username: JuanRRaFdez
          template: streak
          output_path: streak.svg

      - name: Generate Top Languages
        uses: stats-organization/github-readme-stats-action@main
        with:
          username: JuanRRaFdez
          template: top-langs
          output_path: top-langs.svg
