name: GitHub Readme Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Stats
        uses: stats-organization/github-readme-stats-action@main
        with:
          card: stats
          path: stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages
        uses: stats-organization/github-readme-stats-action@main
        with:
          card: top-langs
          path: top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit generated files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add stats.svg top-langs.svg
          git commit -m "Update stats images" || echo "No changes to commit"
          git push
